
exclude:
  - "/vendor/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE.md"
  - "*.gemspec"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"


# Site settings
title: EasyStay
subtitle: "Making Vacations Easy"
url: "http://easystay.vacations" # the base hostname & protocol for your site
# baseurl: "/the/subpath/of/your/site" # Set this value to "" if you want your site to be root
baseurl: ""
cover: "/assets/cover.png"
logo: "/assets/logo.png"
logo_icon: "/img/EasyStay_logo_small.png"

# Build settings
markdown: kramdown

# Google analytics
ga_tracking_id: "UA-117115929-2"

# Category descriptions (for archive pages)
descriptions:
  - cat: guests
    desc: "Posts for EasyStay Guests"

  - cat: hosts
    desc: "Posts for EasyStay Hosts"
